apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zodemo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /node-app
        pathType: Prefix
        backend:
          service:
            name: node-app
            port:
              number: 3000
