apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerone-shop-frontend
  labels:
    app: shop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerone-shop-frontend
  template:
    metadata:
      name: zerone-shop-frontend
      labels:
        app: zerone-shop-frontend
    spec:
      containers:
      - name: zerone-shop-frontend
        image : harbor.birwin.lab/microshop-demo/shop-frontend
        env:
        - name: VITE_API_URL
          value: 'http://10.1.79.58'
        - name: VITE_API_PORT
          value: '5000'
        - name: VITE_JWT_URL
          value: 'http://10.1.79.59'
        - name: VITE_JWT_PORT
          value: '34567'    
        ports:
        - containerPort: 80
      nodeName: kubenode01
      imagePullSecrets:
        - name: regcred