apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: node-app

    
