apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: node-app
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          #image : harbor.birwin.lab/node-app/birwin-node-app:latest
          image : {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
