apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: blue-green
spec:
  selector:
    app: my-app
    version: v1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
